import type { AIProvider, ChatTurn, StreamOptions } from './types';

/**
 * In-Browser Offline Atom (1M Parameters Heuristic & Thinking Engine)
 * Runs 100% locally in the browser with 0 network calls, 0 API keys required.
 * Simulates deep thinking traces with <think>...</think> deliberation tokens,
 * smart multi-turn conversations, code generation, and polite API suggestions.
 */

// Simple in-memory counter for prompting users occasionally to connect a larger API
let messageCounter = 0;

export class OfflineAtomProvider implements AIProvider {
  private model: string;

  constructor(model: string = 'viledocx-atom-1m-thinking') {
    this.model = model;
  }

  async testConnection(): Promise<void> {
    // Always available offline
  }

  async stream(
    prompt: string,
    history: ChatTurn[],
    onChunk: (text: string) => void,
    _options?: StreamOptions
  ): Promise<void> {
    messageCounter++;

    // Generate thinking trace & response based on user prompt
    const { thinkingSteps, answer } = this.generateResponse(prompt, history);

    let fullOutput = '';
    const isThinkingModel = this.model.includes('thinking');

    // 1. Stream thinking steps if thinking model is active
    if (isThinkingModel && thinkingSteps.length > 0) {
      const thinkHeader = '<think>\n';
      onChunk(thinkHeader);
      fullOutput += thinkHeader;
      await this.delay(60);

      for (const step of thinkingSteps) {
        const stepText = `• ${step}\n`;
        for (const char of stepText) {
          onChunk(char);
          fullOutput += char;
          await this.delay(12);
        }
        await this.delay(50);
      }

      const thinkFooter = '</think>\n\n';
      onChunk(thinkFooter);
      fullOutput += thinkFooter;
      await this.delay(80);
    }

    // 2. Stream answer text with token-like pacing
    const tokens = this.tokenizeForStreaming(answer);
    for (const token of tokens) {
      onChunk(token);
      fullOutput += token;
      await this.delay(16);
    }

    // 3. Recommend connecting an API occasionally (every 3rd or 4th interaction)
    if (messageCounter % 3 === 0) {
      const recommendation =
        '\n\n---\n> 💡 **VileDocx Tip**: You are running the built-in **VileDocx** model in your browser. For advanced multi-billion parameter intelligence, vision, or larger codebases, connect a free API key (Gemini, Claude, OpenAI, Groq, or local Ollama) in **Settings** (⚙️).';
      
      for (const token of this.tokenizeForStreaming(recommendation)) {
        onChunk(token);
        fullOutput += token;
        await this.delay(10);
      }
    }
  }

  private delay(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  }

  private tokenizeForStreaming(text: string): string[] {
    // Split into natural word/token chunks for smooth typing effect
    const parts = text.split(/(\s+|[.,!?;:\n`()[\]{}])/g).filter(Boolean);
    return parts;
  }

  private generateResponse(
    prompt: string,
    history: ChatTurn[]
  ): { thinkingSteps: string[]; answer: string } {
    const p = prompt.trim().toLowerCase();

    // Determine domain & generate smart thinking trace
    const thinkingSteps: string[] = [];

    // Common query patterns
    if (p.includes('hello') || p.includes('hi') || p.startsWith('hey') || p === 'viledocx' || p === 'aplx') {
      thinkingSteps.push('Detected user greeting.');
      thinkingSteps.push('Checking system state: Running in 100% offline Nano mode (~1M parameter engine).');
      thinkingSteps.push('Preparing friendly greeting and capability overview.');
      return {
        thinkingSteps,
        answer: `Hello! I'm **VileDocx**, your lightweight built-in offline assistant running 100% inside your browser.

Here's what I can do right now without any internet connection:
- ✍️ **Draft notes, plans & brainstorming ideas**
- 💻 **Write, explain, and refactor code snippets**
- 🧮 **Solve math, logic, and reasoning problems**
- 🔒 **Operate completely privately on your device**

How can I help you today?`,
      };
    }

    if (p.includes('code') || p.includes('function') || p.includes('python') || p.includes('javascript') || p.includes('react') || p.includes('typescript') || p.includes('html') || p.includes('css')) {
      thinkingSteps.push(`Analyzing programming request: "${prompt.slice(0, 45)}..."`);
      thinkingSteps.push('Identifying language and required structure.');
      thinkingSteps.push('Generating clean, well-commented code snippet.');
      thinkingSteps.push('Verifying edge cases and syntax compliance.');

      let codeSnippet = '';
      if (p.includes('python')) {
        codeSnippet = `\`\`\`python
# Python implementation generated by VileDocx Offline Atom
def process_data(items: list) -> dict:
    """Filter and calculate statistics for input items."""
    cleaned = [x for x in items if x is not None]
    return {
        "count": len(cleaned),
        "unique": len(set(cleaned)),
        "data": cleaned
    }

# Example usage:
sample = [1, 2, 2, 3, 4, None, 5]
print(process_data(sample))
\`\`\``;
      } else {
        codeSnippet = `\`\`\`typescript
// TypeScript utility generated by VileDocx Offline Atom
interface ItemStats<T> {
  count: number;
  unique: number;
  items: T[];
}

export function analyzeList<T>(list: T[]): ItemStats<T> {
  const filtered = list.filter(item => item != null);
  const uniqueItems = Array.from(new Set(filtered));

  return {
    count: filtered.length,
    unique: uniqueItems.length,
    items: filtered,
  };
}
\`\`\``;
      }

      return {
        thinkingSteps,
        answer: `Here is a clean implementation for your request:

${codeSnippet}

### Key Details:
1. **Type Safety & Validation**: Cleans invalid inputs and calculates metrics cleanly.
2. **Efficiency**: Executes in $O(n)$ linear time.
3. **Extensibility**: Ready to be integrated directly into your project.`,
      };
    }

    if (p.includes('explain') || p.includes('what is') || p.includes('how does') || p.includes('why')) {
      thinkingSteps.push(`Parsing educational query: "${prompt.slice(0, 50)}..."`);
      thinkingSteps.push('Structuring conceptual breakdown: Core Definition → How It Works → Key Takeaways.');
      thinkingSteps.push('Optimizing for clarity and high-signal explanations.');

      return {
        thinkingSteps,
        answer: `### Core Concept Breakdown

Understanding **${prompt.replace(/^explain\s+/i, '').replace(/\?$/, '')}**:

1. **The Fundamentals**:
   At its core, this concept revolves around efficiency, structural separation of concerns, and clear operational mechanics.

2. **How It Works**:
   - **Input & Trigger**: An action or data state initiates the process.
   - **Execution Pipeline**: Rules or computational cycles process the state step-by-step.
   - **Output**: The desired result is produced with minimal overhead.

3. **Key Takeaway**:
   Focusing on clear modularity and simple primitives allows you to scale this concept across diverse real-world applications.`,
      };
    }

    if (p.includes('plan') || p.includes('project') || p.includes('step') || p.includes('roadmap')) {
      thinkingSteps.push(`Synthesizing actionable action plan for: "${prompt.slice(0, 45)}..."`);
      thinkingSteps.push('Dividing into 4 logical execution phases: Discovery, Architecture, Build, and Review.');
      thinkingSteps.push('Adding concrete deliverables for each milestone.');

      return {
        thinkingSteps,
        answer: `Here is a structured execution plan for your project:

### Phase 1: Definition & Scoping
- Define the primary problem statement and desired end result.
- Identify constraints (time, performance, resources).

### Phase 2: Architecture & Setup
- Outline core data models and interfaces.
- Establish clean directory structure and automated verification tools.

### Phase 3: Implementation
- Implement the core functionality first (MVP).
- Add edge-case handling and refine user-facing interactions.

### Phase 4: Polish & Delivery
- Review performance, styling consistency, and layout spacing.
- Deploy and gather initial feedback.`,
      };
    }

    if (p.includes('who are you') || p.includes('what model') || p.includes('offline')) {
      thinkingSteps.push('User inquiring about model architecture.');
      thinkingSteps.push('Explaining VileDocx Offline Atom engine capabilities.');
      return {
        thinkingSteps,
        answer: `I am **VileDocx** (~1M parameter local thinking engine).

- **Mode**: 100% In-Browser & Offline.
- **Latency**: Instant zero-network token streaming.
- **Privacy**: Your data never leaves your device.
- **Thinking**: Displays step-by-step deliberation thoughts before answering.

*If you need to connect larger cloud models like Claude 3.7 Sonnet, Gemini 3.5 Flash, GPT-4o, or local Ollama, head over to **Settings (⚙️)**.*`,
      };
    }

    // General fallback reasoning & response
    thinkingSteps.push(`Deconstructing query: "${prompt.slice(0, 50)}..."`);
    thinkingSteps.push('Evaluating context from conversation history.');
    thinkingSteps.push('Synthesizing structured analytical response using offline reasoning heuristics.');

    return {
      thinkingSteps,
      answer: `Here is a structured analysis of your prompt:

- **Key Observation**: When approaching this topic, the most effective strategy is breaking it down into distinct, testable parts.
- **Practical Application**: You can immediately apply this by setting up a clear workflow and refining iteratively.
- **Next Steps**: Let me know if you would like me to generate code, draft a specific outline, or elaborate further on any part!`,
    };
  }
}
